### ISSUE TITLE
关于Live2D.dll

### ISSUE THREAD

**Issue by rinkako** [ytx1991/Azusa-Live2D#1]
你好！我最近在开发一个基于C#的AVG，需要用到Live2D的功能，但官方SDK没有提供这样的API，发现您这个项目的Live2D.DLL是可以由C#程序调用的，请问您这个项目中的Live2D.DLL文件，能否授权给我们进行非商业使用？或者是否可以开放源代码，或者提供一下调用接口呢？非常感谢！
Hi! Our team is now developing an AVG based on C#, which need Live2D, while the SDK doesn't provide such API. We found that the Live2D.dll in your project maybe very useful in our project, hence we would like to know if this dll library can be use in our own project? Thanks!

**Comment by ytx1991** [comment]
你们是个人还是组织，具体什么用途，虽然代码是我写的但这只是一个project的UI部分，那个project有另一帮人在维护，我不清楚授权给你会不会影响他们

**Comment by rinkako** [comment]
是一个2-3人的小团体，开发非商业化的免费AVG游戏。如果可以得到授权，项目完成时会在STAFF名单中明显位置标明出处或者要求书写的文字~

**Comment by ytx1991** [comment]
那你们先拿去用吧，完了staff 加上 Tianxiang Yu

**Comment by rinkako** [comment]
好的，非常感谢！因为dll没有开源，所以能否提供一下相应的接口？

**Comment by rinkako** [comment]
附邮箱地址：jiajidi@163.com  非常感谢！

**Comment by copytime** [comment]
你好！同样的问题，我是一个 Live2D 的爱好者，目前正在研究 Live2D 的 C# 实现，请问能否可以获得您的许可并提供相应的接口呢？当然并不会进行任何的商业活动。
非常感谢！
